### PR TITLE
Allow Dimension response

### PR DESCRIPTION
**Pull request by cgoessen**
This allow "Dimension responses" to be parsed.

### CODE REVIEW

**Comment by badosa** [comment]
> This allow "Dimension responses" to be parsed.

Really? Did you try it against a dimension response? Do you have a working example?

I checked your request and it doesn't seem to work as expected (I can point two or three places in the code that also require changes).

**Comment by cgoessen** [comment]
You are right, I was to quick to judge.

This doesn't return a valid dimension response. I was so focused on getting rid of the processing error I did not pay attention to the return value.

I'll look into it if I can figure out what's wrong.

**Comment by badosa** [comment]
If you want, I can take care of it (in a week or so).

**Comment by cgoessen** [comment]
That would be much appreciated, I'm still trying to figure out your code.
You'd be more efficient at this one for sure.

**Pull request closed without merging**
